# environment.yml
# Conda environment definition for the basic roguelike project.

name: basicrl

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy>=1.23
  - polars>=0.19
  - numba>=0.57
  - orjson>=3.9
  - pyyaml>=6.0
  - pip
#  - pip:
      # Add pip-installed packages below as needed
      # - tdl
