[tool.black]
line-length = 100
target-version = ["py310"]
skip-string-normalization = false

[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint]
select = ["I", "E", "F", "B", "UP"]
fixable = ["ALL"]
